# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# boundline_model_script.py
# Created on: 2015-02-04 18:32:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

arcpy.env.overwriteOutput = 1 # Important for debugging; won't freak out about files existing already.

# Local variables:
fileInput = arcpy.GetParameterAsText(0)
boundline = arcpy.GetParameterAsText(1)
dissolve = "dissolve"

# Process: Dissolve
arcpy.Dissolve_management(fileInput, dissolve, "", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Polygon To Line
arcpy.PolygonToLine_management(dissolve, boundline, "IDENTIFY_NEIGHBORS")

# Output test
mxd = arcpy.mapping.MapDocument("CURRENT")
data_frame = arcpy.mapping.ListDataFrames(mxd, "*")[0]
add_layer = arcpy.mapping.Layer(boundline)
arcpy.mapping.AddLayer(data_frame,add_layer)

# Remove intermediate files from memory
arcpy.Delete_management(dissolve)
