# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# boundline_model_script.py
# Created on: 2015-02-04 18:32:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

arcpy.env.overwriteOutput = 1 # Important for debugging; won't freak out about files existing already.

# Local variables:
fileInput = arcpy.GetParameterAsText(0)
boundline = arcpy.GetParameterAsText(1)
simpleFile = arcpy.GetParameterAsText(2)
spatial_ref = arcpy.Describe(fileInput).spatialReference
vertices = arcpy.GetParameterAsText(3)
#vertices = "vertices"

# Simplify dataset
arcpy.SimplifyPolygon_cartography(fileInput,simpleFile,"POINT_REMOVE",50,"","RESOLVE_ERRORS")

# Get vertices for dataset
arcpy.FeatureVerticesToPoints_management(fileInput, vertices, "ALL")

# Create bound using TIN
#arcpy.CreateTin_3d(bound_tin, spatial_ref, "vertices, <None>, hardclip")